version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "18:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  reviewers:
  - quittle
  assignees:
  - quittle
  labels:
  - dependencies
  ignore:
  - dependency-name: com.github.triplet.play
    versions:
    - 3.1.0-agp4.2
    - 3.2.0-agp4.2-2
    - 3.3.0-agp4.2
