version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "18:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  reviewers:
  - quittle
  assignees:
  - quittle
  labels:
  - dependencies
